version: '3.8'

services:
  postgres:
    image: postgres:14
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=api
    ports:
      - '5432:5432'
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
    